language: minimal
sudo: required
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - REPO_NAME=your-thesis-statement
  - GCR_REPO=gcr.io/kubernetes-221218
  - HELM_RELEASE=donating-bobcat
  - HELM_CHART_DIR=helm/your-thesis-statement
before_install:
- openssl aes-256-cbc -K $encrypted_bda615ba7c7a_key -iv $encrypted_bda615ba7c7a_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar -zxf secrets.tar.gz
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then rm -rf $HOME/google-cloud-sdk; curl
  https://sdk.cloud.google.com | bash > /dev/null; fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud version
script:
- docker build -t $REPO_NAME:latest .
before_deploy:
- scripts/install_helm.sh
cache:
  directories:
  - "$HOME/google-cloud-sdk"
deploy:
- provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    repo: tanelso2/your_thesis_statement
    branch: master
