version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - aws s3 cp s3://your-thesis-statement/secret.json .
  pre_build:
    commands:
      - chmod +x create_deployment.sh
  build:
    commands:
      - docker build .
      - ./create_deployment.sh
artifacts:
  files:
    - "**/*"
