# TODO: Cleanup env variable definitions
name: Docker Image CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "${GSPREAD_ACCESS_JSON}" > secret.json
      shell: bash
      env:
        GSPREAD_ACCESS_JSON: ${{secrets.GSPREAD_ACCESS_JSON}}
    - run: echo "${GCR_SERVICE_ACCOUNT}" > service-account.json
      shell: bash
      env:
        GCR_SERVICE_ACCOUNT: ${{secrets.GCR_SERVICE_ACCOUNT}}
    - uses: tanelso2/deployment_scripts/actions/install_gcloud@master
    # - run: curl https://sdk.cloud.google.com | bash > /dev/null
    #   env:
    #     CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
    #     REPO_NAME: your-thesis-statement
    #     GCR_REPO: gcr.io/kubernetes-221218
    - uses: tanelso2/deployment_scripts/actions/build_and_push_to_gcr@master
      with:
        repoName: your-thesis-statement
    # - run: wget https://raw.githubusercontent.com/tanelso2/deployment_scripts/master/push_image_to_gcr.sh
    # - run: chmod +x push_image_to_gcr.sh
    # - run: ./push_image_to_gcr.sh
    #   env:
    #     CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
    #     REPO_NAME: your-thesis-statement
    #     GCR_REPO: gcr.io/kubernetes-221218
