name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "${GSPREAD_ACCESS_JSON}" > secret.json
      shell: bash
      env:
        GSPREAD_ACCESS_JSON: ${{secrets.GSPREAD_ACCESS_JSON}}
    - uses: tanelso2/deployment_scripts/actions/build_image@main
      with:
        repoName: findmythesis
    - uses: tanelso2/deployment_scripts/actions/build_and_push_to_gcr@main
      id: gcr
      with:
        repoName: findmythesis
        serviceAccount: ${{secrets.GCR_SERVICE_ACCOUNT}}
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    - uses: tanelso2/deployment_scripts/actions/update_tcm@main
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        repoName: findmythesis
        tcmKey: ${{secrets.TCM_KEY}}
        tcmAddr: tcm.thomasnelson.me
        imageTag: ${{steps.gcr.outputs.tag}}
