name: Docker Image CI

on:
  push:
    branches: [ tnelson/cicd ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:
      - echo "${GSPREAD_ACCESS_JSON}" > secret.json
      - docker build . --file Dockerfile --tag my-image-name:gh-$(date +%s)
