name: Docker Image CI

on:
  push:
    branches: [ tnelson/cicd ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "${GSPREAD_ACCESS_JSON}" > secret.json
      shell: bash
      env:
        SSH_KEY: ${{secrets.GSPREAD_ACCESS_JSON}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:gh-$(date +%s)
