name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "${GSPREAD_ACCESS_JSON}" > secret.json
      shell: bash
      env:
        GSPREAD_ACCESS_JSON: ${{secrets.GSPREAD_ACCESS_JSON}}
    - uses: tanelso2/deployment_scripts/actions/build_image@main
      with:
        repoName: your-thesis-statement
    - uses: tanelso2/deployment_scripts/actions/build_and_push_to_gcr@main
      with:
        repoName: your-thesis-statement
        serviceAccount: ${{secrets.GCR_SERVICE_ACCOUNT}}
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    - uses: tanelso2/deployment_scripts/actions/update_tcm@main
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      with:
        repoName: your-thesis-statement
        tcmKey: ${{secrets.TCM_KEY}}
        tcmAddr: tcm-bender.thomasnelson.me
