# TODO: Cleanup env variable definitions
name: Docker Image CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: tanelso2/deployment_scripts/actions/install_gcloud@master
    - run: echo "${GSPREAD_ACCESS_JSON}" > secret.json
      shell: bash
      env:
        GSPREAD_ACCESS_JSON: ${{secrets.GSPREAD_ACCESS_JSON}}
    - uses: tanelso2/deployment_scripts/actions/build_and_push_to_gcr@master
      with:
        repoName: your-thesis-statement
        serviceAccount: ${{secrets.GCR_SERVICE_ACCOUNT}}
